/* tslint:disable */
/* prettier:disable */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import { HttpClient, HttpResponse } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { GameRequest } from "../routes/management/game/game-new/game-new.component";
import { CategoryRequest } from "../routes/management/category/category-new/category-new.component";

@Injectable()

/**
 * Generated client library for MessagingPricesService.
 */
export class SeriousGameService {
    public static Url: string;

    constructor(private http: HttpClient) {
        if (!SeriousGameService.Url) {
            throw new Error("SeriousGameService.Url is not set.");
        }

        // if (SeriousGameService.Url[SeriousGameService.Url.length - 1] !== "/") {
        //     SeriousGameService.Url += "/";
        // }
    }

    private static query(arg: string[]): string {
        if (!arg) {
            return "";
        }
        let result = "";
        arg.forEach((a) => {
            if (a) {
                result += (result ? "&" : "?") + a;
            }
        });
        return result;
    }

    /**
     * Get all games
     * @returns An observable on the XHR request
     */
    public getAllGames(): Observable<Game[]> {
        return this.http
            .get(`${SeriousGameService.Url}/game`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game[]>) => r.body));
    }

    /**
     * Get game by game pin
     * @param pin: GamePin
     * @returns An observable on the XHR request
     */
    public getGameByPin(pin: number): Observable<Game> {
        return this.http
            .get(`${SeriousGameService.Url}/game/${pin}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Get all game pins
     * @returns An observable on the XHR request
     */
    public getAllGamePins(): Observable<number[]> {
        return this.http
            .get(`${SeriousGameService.Url}/game/gamepin`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<number[]>) => r.body));
    }

    /**
     * Edit a game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public editGame(game: Game): Observable<Game> {
        return this.http
            .put(`${SeriousGameService.Url}/game/${game.pin}`, game, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Post a new game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public postGame(game: GameRequest): Observable<Game> {
        return this.http
            .post(`${SeriousGameService.Url}/game`, game, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Delete a game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public deleteGame(game: Game): Observable<Game[]> {
        return this.http
            .delete(`${SeriousGameService.Url}/game/${game.pin}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game[]>) => r.body));
    }

    /**
     * Get all categories
     * @returns An observable on the XHR request
     */
    public getAllCategories(): Observable<Category[]> {
        return this.http
            .get(`${SeriousGameService.Url}/category`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category[]>) => r.body));
    }

    /**
     * Post a new category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public postCategory(category: CategoryRequest): Observable<Category> {
        return this.http
            .post(`${SeriousGameService.Url}/category`, category, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category>) => r.body));
    }

    /**
     * Edit a category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public editCategory(category: Category): Observable<Category> {
        return this.http
            .put(
                `${SeriousGameService.Url}/category/${category._id}`,
                category,
                {
                    observe: "response",
                }
            )
            .pipe(map((r: HttpResponse<Category>) => r.body));
    }

    /**
     * Delete a category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public deleteCategory(category: Category): Observable<Category[]> {
        return this.http
            .delete(`${SeriousGameService.Url}/category/${category._id}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category[]>) => r.body));
    }

    // STATISTICS

    /**
     * Get Average Score per category, per game
     * @returns An observable on the XHR request
     */
    public getAvgScorePerCat(): Observable<MultiChartData[]> {
        return this.http
            .get(`${SeriousGameService.Url}/stats/avgScorePerCat`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<MultiChartData[]>) => r.body));
    }

    /**
     * Get Average Score for players, for all games
     * @returns An observable on the XHR request
     */
    public getAvgPlayer(amountOfPlays?: number): Observable<MultiChartData[]> {
        const queryParams: string[] = [];
        if (amountOfPlays) {
            queryParams.push(`limit=${amountOfPlays}`);
        }
        return this.http
            .get(
                `${
                    SeriousGameService.Url
                }/stats/avgPlayer${SeriousGameService.query(queryParams)}`,
                {
                    observe: "response",
                }
            )
            .pipe(map((r: HttpResponse<MultiChartData[]>) => r.body));
    }

    /**
     * Get Average Score per category, per game
     * @param gamePin: Game Pin
     * @returns An observable on the XHR request
     */
    public getPlaysPerDay(gamePin: number): Observable<PlaysPerDay[]> {
        return this.http
            .get(`${SeriousGameService.Url}/stats/${gamePin}/playsPerDay`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<PlaysPerDay[]>) => r.body));
    }

    /**
     * Get Top Play for game pin
     * @param gamePin: Game Pin
     * @returns An observable on the XHR request
     */
    public getTopPlay(gamePin: number): Observable<Play> {
        return this.http
            .get(`${SeriousGameService.Url}/stats/${gamePin}/topPlay`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Play>) => r.body));
    }

    /**
     * Get Worst Play for game pin
     * @param gamePin: Game Pin
     * @returns An observable on the XHR request
     */
    public getWorstPlay(gamePin: number): Observable<Play> {
        return this.http
            .get(`${SeriousGameService.Url}/stats/${gamePin}/minPlay`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Play>) => r.body));
    }

    /**
     * Get the question category distribution
     * @param gamePin: Game Pin
     * @returns An observable on the XHR request
     */
    public getPercentageQuestions(
        gamePin: number
    ): Observable<MultiChartData[]> {
        const queryParams: string[] = [];
        if (gamePin) {
            queryParams.push(`pin=${gamePin}`);
        }
        return this.http
            .get(
                `${
                    SeriousGameService.Url
                }/stats/percentageQuestions${SeriousGameService.query(
                    queryParams
                )}`,
                {
                    observe: "response",
                }
            )
            .pipe(map((r: HttpResponse<MultiChartData[]>) => r.body));
    }
}

export interface Game {
    _id?: number;
    pin?: number;
    description?: string;
    totalPlays?: number;
    questions?: Question[];
    createdAt?: Date;
    updatedAt?: Date;
    lastPlayed?: Date;
    ___v?: number;
}

export interface Question {
    _id?: string;
    question?: string;
    category?: string;
    answers?: Answer[];
    level?: number;
}

export interface Answer {
    _id?: string;
    answer?: string;
    deltaScore?: number;
}

export interface Category {
    _id?: string;
    name?: string;
    createdAt?: Date;
    updatedAt?: Date;
    ___v?: number;
}

export interface MultiChartData {
    name: string;
    series: {
        name: string;
        value: number;
    }[];
}

export interface PlaysPerDay {
    name: string;
    value: number;
}

export interface Play {
    _id?: string;
    pin?: number;
    scores?: {
        category?: string;
        score?: number;
    }[];
}
