/* tslint:disable */
/* prettier:disable */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import { HttpClient, HttpResponse } from "@angular/common/http";
import { Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { GameRequest } from "../routes/management/game/game-new/game-new.component";
import { CategoryRequest } from "../routes/management/category/category-new/category-new.component";

@Injectable()

/**
 * Generated client library for MessagingPricesService.
 */
export class SeriousGameService {
    public static Url: string;

    constructor(private http: HttpClient) {
        if (!SeriousGameService.Url) {
            throw new Error("SeriousGameService.Url is not set.");
        }

        // if (SeriousGameService.Url[SeriousGameService.Url.length - 1] !== "/") {
        //     SeriousGameService.Url += "/";
        // }
    }

    private static query(arg: string[]): string {
        if (!arg) {
            return "";
        }
        let result = "";
        arg.forEach((a) => {
            if (a) {
                result += (result ? "&" : "?") + a;
            }
        });
        return result;
    }

    /**
     * Get all games
     * @returns An observable on the XHR request
     */
    public getAllGames(): Observable<Game[]> {
        return this.http
            .get(`${SeriousGameService.Url}/game`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game[]>) => r.body));
    }

    /**
     * Get game by game pin
     * @param pin: GamePin
     * @returns An observable on the XHR request
     */
    public getGameByPin(pin: number): Observable<Game> {
        return this.http
            .get(`${SeriousGameService.Url}/game/${pin}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Edit a game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public editGame(game: Game): Observable<Game> {
        return this.http
            .put(`${SeriousGameService.Url}/game/${game.pin}`, game, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Post a new game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public postGame(game: GameRequest): Observable<Game> {
        return this.http
            .post(`${SeriousGameService.Url}/game`, game, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game>) => r.body));
    }

    /**
     * Delete a game
     * @param game: Game object
     * @returns An observable on the XHR request
     */
    public deleteGame(game: Game): Observable<Game[]> {
        return this.http
            .delete(`${SeriousGameService.Url}/game/${game.pin}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Game[]>) => r.body));
    }

    /**
     * Get all categories
     * @returns An observable on the XHR request
     */
    public getAllCategories(): Observable<Category[]> {
        return this.http
            .get(`${SeriousGameService.Url}/category`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category[]>) => r.body));
    }

    /**
     * Post a new category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public postCategory(category: CategoryRequest): Observable<Category> {
        return this.http
            .post(`${SeriousGameService.Url}/category`, category, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category>) => r.body));
    }

    /**
     * Edit a category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public editCategory(category: Category): Observable<Category> {
        return this.http
            .put(
                `${SeriousGameService.Url}/category/${category._id}`,
                category,
                {
                    observe: "response",
                }
            )
            .pipe(map((r: HttpResponse<Category>) => r.body));
    }

    /**
     * Delete a category
     * @param category: Category object
     * @returns An observable on the XHR request
     */
    public deleteCategory(category: Category): Observable<Category[]> {
        return this.http
            .delete(`${SeriousGameService.Url}/category/${category._id}`, {
                observe: "response",
            })
            .pipe(map((r: HttpResponse<Category[]>) => r.body));
    }

    // /**
    //  * Get all departments from the given Organisation
    //  * @param orgId Organisation ID (the Organisation PIN &#x3D; Organisation ID)
    //  * @returns An observable on the XHR request
    //  */
    // public getAllDepartmentsFromOrganisation(
    //     orgId: number
    // ): Observable<Department[]> {
    //     return this.http
    //         .get(`${SeriousGameService.Url}/organisation/${orgId}/department`, {
    //             withCredentials: true,
    //             observe: "response",
    //         })
    //         .pipe(map((r: HttpResponse<Department[]>) => r.body));
    // }

    // /**
    //  * Gets the top routes per operator.
    //  * @param operatorMncMcc The operator MNC MCC.
    //  * @param amount The amount (default 5)
    //  * @returns An observable on the XHR request
    //  */
    // public getTopRoutesPerOperator(data: {
    //     operatorMncMcc: number;
    //     amount?: number;
    // }): Observable<IApiSMSTopRoutes[]> {
    //     const queryParameters: string[] = [];
    //     if (
    //         data &&
    //         data.operatorMncMcc !== undefined &&
    //         data.operatorMncMcc !== null
    //     )
    //         queryParameters.push(`operatorMncMcc=${data.operatorMncMcc}`);
    //     if (data && data.amount !== undefined && data.amount !== null)
    //         queryParameters.push(`amount=${data.amount}`);
    //     return this.http
    //         .get(
    //             `${
    //                 MessagingPricesService.Url
    //             }messagingprices/v1.0/sms/routes${MessagingPricesService.query(
    //                 queryParameters
    //             )}`,
    //             { withCredentials: true, observe: "response" }
    //         )
    //         .pipe(map((r: HttpResponse<IApiSMSTopRoutes[]>) => r.body));
    // }

    // /**
    //  * Gets the top operators per country
    //  * @param mcc The Country MCC
    //  * @param amount Amount of operators
    //  * @returns An observable on the XHR request
    //  */
    // public getTopOperatorsPerCountry(data: {
    //     mcc: number;
    //     amount?: number;
    // }): Observable<IApiTopOperatorsPerCountry[]> {
    //     const queryParameters: string[] = [];
    //     if (data && data.mcc !== undefined && data.mcc !== null)
    //         queryParameters.push(`mcc=${data.mcc}`);
    //     if (data && data.amount !== undefined && data.amount !== null)
    //         queryParameters.push(`amount=${data.amount}`);
    //     return this.http
    //         .get(
    //             `${
    //                 MessagingPricesService.Url
    //             }messagingprices/v1.0/sms/operators${MessagingPricesService.query(
    //                 queryParameters
    //             )}`,
    //             { withCredentials: true, observe: "response" }
    //         )
    //         .pipe(
    //             map((r: HttpResponse<IApiTopOperatorsPerCountry[]>) => r.body)
    //         );
    // }

    // /**
    //  * Drops the Cache
    //  * @returns An observable on the XHR request
    //  */
    // public dropCache(data: {} = {}): Observable<any> {
    //     return this.http
    //         .delete(
    //             `${MessagingPricesService.Url}messagingprices/v1.0/util/cache`,
    //             { withCredentials: true, observe: "response" }
    //         )
    //         .pipe(map((r: HttpResponse<any>) => r.body));
    // }
}

export interface Game {
    _id?: number;
    pin?: number;
    description?: string;
    amountOfPlays?: number;
    questions?: Question[];
    createdAt?: Date;
    updatedAt?: Date;
    ___v?: number;
}

export interface Question {
    _id?: string;
    question?: string;
    category?: string;
    answers?: Answer[];
    level?: number;
}

export interface Answer {
    _id?: string;
    answer?: string;
    deltaScore?: number;
}

export interface Category {
    _id?: string;
    name?: string;
    createdAt?: Date;
    updatedAt?: Date;
    ___v?: number;
}
